### ISSUE TITLE
Set up "preview page" Action

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/Salinity_SOP#44]
Before starting the community review we should set up this action. This will make the review process easier for the maintainers as errors are found faster.

**Comment by soerenthomsen** [comment]
I set it up again but as it looks like the URL is not shown.

**Comment by soerenthomsen** [comment]
Maybe @jbusecke knows what the problem is?

**Comment by jbusecke** [comment]
What exactly do you mean by "the URL is not shown?"

**Comment by jbusecke** [comment]
I think the problem is [here](https://github.com/OceanGlidersCommunity/Salinity_SOP/runs/4238062600?check_suite_focus=true#step:10:11)

You will have to set up a separate netlify site and add the login infos as secrets to this repo, just like in the oxygen one.

**Comment by soerenthomsen** [comment]
> What exactly do you mean by "the URL is not shown?"

In the conversation of the pull-requests there is no link behind the URL!

**Comment by soerenthomsen** [comment]
Let's fix this tomorrow also for Nitrate, which i just uploaded :)

**Comment by jbusecke** [comment]
Sure, just ring me up and we can figure it out.

**Comment by soerenthomsen** [comment]
Fixing this by setting up a new page on netlifly and stop building it, and create TOKEN and IP in repo secrets

**Comment by soerenthomsen** [comment]
Works now. Tested with PR #104
