### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by LouClement** [OceanGlidersCommunity/Salinity_SOP#58]
- [x] Section 3.1.1.1
Replace
The CT-Sail is a free-flushed (unpumped) CTD (SBE41) was the
By
The CT-Sail, a free-flushed (unpumped) CTD (SBE41), was the

dealt with in #60 

- [x] #61

- [x] Title Section 3.2. Sensor integrations, not integratons

dealt with in #60 

- [x] Section 4.1
Most users send their CT-sensors

dealt with in #60 

- [x] Replace
because of how it is directly integrated into the glider fairing
By
because of its direct integration into the glider fairing

- [x] Replace
In the case of RBRlegato3, because it is inductive, only field calibration or by relying on Alseamar/SeaExplorer’s coefficients to correct for the influence of the vehicle on the sensor’s inductive field is possible. Accuracy of that coefficient is unproven. Recommended strategy is deep CTD in proximity. This is problematic in shallow dynamic shelf sea waters.

By
For the RBRlegato3 sensor with an inductive cell, the calibrations can only be done in the field or by using the SeaExplorer’s coefficients that correct the influence of the vehicle on the sensor’s inductive field. The accuracy of these coefficients is unproven. The recommended strategy is to sample deep CTD in proximity, which becomes problematic in shallow dynamic shelf sea waters.

-> dealt with in #62 

- [x] #63
Replace 
Biofouling that can affect salinity through
By
Biofouling can affect salinity by … and by 2) affecting the flight model, which estimates the glider’s speed assuming a steady flight in still water.
Did you mean anything specific by ‘2) depending on how the flight model is implemented’?

- [x] Replace
of the biofouling on the fli model
By
of biofouling on the flight model

- [x] Add one bracket in
(see Section 8.1)

- [x] #64
Replace
Those reference data should be found in the same regional basin with respect to the local circulation pattern.
By
Those reference data should preferentially sample the same regional basin and be affected by the same circulation.

- [x] Replace
Ideally and when possible, deep data from profiles from the offshore area where water mass variability is smaller should be used.
By
Ideally, offshore deep profiles sampling water mass with low variability in their properties should be used.

- [x] Section 5.3.2
Remove bracket of
CTD cast)

- [x] Title of section 8.3, inter-comparison not inter-comparsion

**Comment by soerenthomsen** [comment]
Thanks a lot @LouClement for this detailed review! I will implement these typos now and create pull-requests and link them in your comment.

**Comment by soerenthomsen** [comment]
Fine to close this or @isgiddy ?
