### ISSUE TITLE
GitHub handle for Mathieu Dever

### ISSUE THREAD

**Issue by matdever** [OceanGlidersCommunity/Salinity_SOP#78]
A gitHub handle can be added for MAthieu Dever in Section 1 

https://github.com/matdever

**Comment by soerenthomsen** [comment]
Thanks @matdever for your input! I suggest you add your GitHub handle via a pull-request directly to this file: https://github.com/OceanGlidersCommunity/Salinity_SOP/blob/main/sections/authors_SOP_development_process.md 

Like this you will also be listed on GitHub as contributor! 

The other issue's we will take care of!
