### ISSUE TITLE
Seabird unpumped CTD for Slocum gliders

### ISSUE THREAD

**Issue by truedichotomy** [OceanGlidersCommunity/Salinity_SOP#88]
I know a number of users still use unpumped CTD from Seabird on their Slocum gliders. There is also a large repository of data from that platform/sensor combination. It would be good to address it in this SOP I think.

**Comment by soerenthomsen** [comment]
Thanks @truedichotomy actually we cover it but the tick is gone somehow. Will add it thanks. 
This also relates to this issues #47 

PS: @truedichotomy could you link your GitHub page to the author list via a pull-request? Like this you are also listed here as a contributor. Thanks!

**Comment by soerenthomsen** [comment]
I created a pull-request #94 so we can go ahead.

**Comment by soerenthomsen** [comment]
Will close this and direct all discussions to #47
